[[redirects]]
  from = "/cs"
  to = "/cs/:splat"
  status = 302

[[redirects]]
  from = "/en"
  to = "/en/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/cs/:splat"
  status = 302
  conditions = {Language = ["cs"]}

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
